name: Commit Action
on: [push, pull_request]
jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [18.x]
    steps:
      - uses: actions/checkout@v3
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install modules
        run: npm install
      - 
        name: Lint code
        run: npm run lint:check
      - 
        name: Prettier check
        run: npm run prettier:check
      - 
        name: TypeScript check
        run: npm run type:check
      - 
        name: Build
        run: npm run build:check
